### PR TITLE
[WIP] Track Changes To Mutable Traits

### PR DESCRIPTION
**Pull request by rmorshea**
a work in progress @martinRenou

### CODE REVIEW

**Comment by martinRenou** [comment]
Awesome! The big step would be to have `ipywidgets` support this kind of events in messages.

**Comment by rmorshea** [comment]
@martinRenou for some reason I though `ipywidgets` already depended on `traittypes`. Should this PR just move to `ipywidgets` or does it make sense to put it here and then add `traittypes` as a dependency of `ipywidgets`?

**Comment by martinRenou** [comment]
I suppose it makes sense opening the PR here. The thing is that we would need new kinds of messages in ipywidgets.

ipywidgets sends a message whenever the value of an attribute has been overwritten, not when the value has been altered. So it's a change in the ipywidgets messaging protocol that we must do for fully supporting this kind of features...

Also if we want to fully support it we need a spectate equivalent JS side.

I suppose having spectate in traittypes is a good starting point.

**Comment by rmorshea** [comment]
Maybe this should go into `ipywidgets` if the communication protocol will change (event though I don't think you need to do that initially). For now, I think it's fine to just resend the whole trait value each time it's mutated. In the future we can work to update the protocol so you can communicate diffs instead.

**Comment by rmorshea** [comment]
Closing for now. I don't expect I'll get to this one.

**Pull request closed without merging**
